AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation template for roman numerals web app
  
Parameters:

  KeyPair:
    Description: Key Pair for EC2 instance
    Type: AWS::EC2::KeyPair::KeyName

  
Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable HTTP and SSH for webserver
      GroupName: WebServerSecGrp
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0


  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags: 
        - Key: Name
          Value: WebServer2-Merve
      UserData:
      |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        

        

  
  
#Outputs: