AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation template to deploy the Roman Numeral Converter web application
# Parameters:
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH for webserver
      GroupName: WebserverSecGrp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0b5eea76982371e91" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebServer-Merve
      UserData:
        Fn::Base64:
        |
          #! /bin/bash
          yum update -y
          yum install python3 -y
          pip3 install flask
          yum install git -y
          cd /home/ec2-user
          wget -P templates https://raw.githubusercontent.com/serdarcw/cli_deneme/master/templates/index.html
          wget -P templates https://raw.githubusercontent.com/serdarcw/cli_deneme/master/templates/result.html
          wget https://raw.githubusercontent.com/serdarcw/cli_deneme/master/app.py
          python3 app.py
